// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type NewTodo struct {
	Text   string          `json:"text"`
	UserID string          `json:"userId"`
	File   *graphql.Upload `json:"file,omitempty"`
}

type Todo struct {
	ID     string `json:"id"`
	Text   string `json:"text"`
	Done   bool   `json:"done"`
	FileID string `json:"fileID"`
	User   *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
